### ISSUE TITLE
IE support?

### ISSUE THREAD

**Issue by pstoica** [jhollingworth/marty#100]
Hey, I'm interested in using this! But I noticed the builds have been failing for IE. Sorry I haven't tested myself, but is this indicative of IE support or should it be good to use?

**Comment by jhollingworth** [comment]
Hey, it's been working until I upgraded to the latest ``isomorphic-fetch``. It's top of my list to work on right. Will let you know when its fixed (Hopefully day or two)

**Comment by jhollingworth** [comment]
IE Support is now back. Technically it never went away, it was just the tests were broken
