### ISSUE TITLE
Two Marty State Mixins cause onStoreChanged invariant violation

### ISSUE THREAD

**Issue by dariocravero** [jhollingworth/marty#102]
Hi all,

I'm trying to figure out as to whether this is: a) properly done :), b) a Marty issue or a c) React issue.

How do you deal with two State Mixins pulling state from different stores and trying to be mixed into the same view?

[Here's a gist showcasing the issue](https://gist.github.com/dariocravero/3d56bec82ee96c4d7684).

Given two StateMixins:
```
var EditableState   = Marty.createStateMixin({
  listenTo: EditableStore,
 
  getState: function() {
    return {
      editable: EditableStore.isEditable()
    };
  }
});
var BlockState = Marty.createStateMixin({
  listenTo: BlockStore,
 
  getState: function() {
    return {
      block: BlockStore.getBlock(this.props.blockId)
    };
  }
});
```

And a view that uses them:
```
var View = React.createClass({
  mixins: [
    BlockState,
    EditableState
  ],
 
  render: function() {
    return <div>A view</div>;
  }
});
```

The view fails with `Uncaught Error: Invariant Violation: ReactCompositeComponentInterface: You are attempting to define `onStoreChanged` on your component more than once. This conflict may be due to a mixin.`.

Is this the wrong approach? Or maybe it's a Marty or a React issue?

When Googling the symptoms I found this facebook/react#375 but it's not strictly related, plus there are no `Policy`s being enforced in for `onStoreChanged` unless it's a default?

Thanks!
Darío

**Comment by dariocravero** [comment]
After [this simplified example](https://gist.github.com/dariocravero/3d56bec82ee96c4d7684), I think this is either a bad practice or a React issue. facebook/react#3027

**Comment by jhollingworth** [comment]
Hey, a the StateMixin can listen to multiple stores

```js
var ViewState = Marty.createStateMixin({
  listenTo: [EditableStore, BlockStore],

  getState: function() {
    return {
      editable: EditableStore.isEditable(),
      block: BlockStore.getBlock(this.props.blockId)
    };
  }
});
var View = React.createClass({
  mixins: [ViewState],
  render: function() {
    return <div>A view</div>;
  }
});
```

**Comment by dariocravero** [comment]
I wanted to make the editable listener a reusable mixin because it will be used throughout many views that may or may not share the same mixin but in all fairness the overload isn't that big and it probably makes sense to do that... :) Thanks
