### ISSUE TITLE
Question related to swallowing non fetch related exceptions in StateSources

### ISSUE THREAD

**Issue by dariocravero** [jhollingworth/marty#120]
We had a [funky circular reference issue](https://github.com/dariocravero/circular-ref-issue) just a while ago and the error would bubble up through the `failed` status of `fetch`. Basically the action creator was undefined and the call to `UserSourceActionCreators.receiveUser(res.body);` obviously failed.
However, this was an issue with our code and not an exception in the flow itself. Should those kind of exceptions be thrown into the wild and not handled by the promise?

**Comment by oliverwoodings** [comment]
Not quite sure how you would achieve this - is it even possible to throw an exception and not have it bubble when inside a promise chain?

**Comment by jhollingworth** [comment]
Yeah, don't think theres a way to distinguish between the two...
