### ISSUE TITLE
TTL / Cache Invalidation

### ISSUE THREAD

**Issue by prayerslayer** [jhollingworth/marty#121]
Hey, first of all I wanted to thank you for your work, I really appreciate it.

My question is this: The `FetchResult` makes many things easier and caching the result of a fetch is what you want most of the time. However depending on your domain objects you want to re-fetch data sooner or later. I don't know, let's say a weather app. The geographic locations are quite long-lived, they are fine to be in the cache even for days. But the weather forecast may change significantly during a few hours, so you want to make sure to always show data that's not older than `x` minutes.

Okay, now the actual question: Would it be feasible to keep a timestamp of a [`fetchId`](http://martyjs.org/api/stores/#hasAlreadyFetched), capturing when it was last fetched? This could then be used to specify a `ttl` on a fetch. The local data is invalidated if `now - ttl > time of last fetch` and a new fetch is queued.

Or do you think it is something that should be left upon the users of the framework to implement?

**Comment by jhollingworth** [comment]
First off thanks :) Nice to hear people are liking Marty

This question has come up a few times actually (Probably time I [write up a guide about it](https://github.com/jhollingworth/marty/issues/122)). So my opinion is that the fetch API is designed for dealing with getting state from cache and what should happen when you have a cache miss. While related, I think cache invalidating is independent of cache population.

I completely get where you're coming from with the ``ttl`` however that is a state change and so should go through an action for it to conform to the unidirectional data flow. I would suggest having a separate action creator that is responsible for invalidating the cache. When you receive the state in the source action creator you could set a timeout which then calls that action.

**Comment by prayerslayer** [comment]
Hey, sorry for being late. Thanks for clarifying. Also the discussion in #80 helped me a lot.
