### ISSUE TITLE
CORS requests with HttpStateSource

### ISSUE THREAD

**Issue by doesnotexist** [jhollingworth/marty#125]
It is not clear how one would go about sending a CORS request using the HttpStateSource.  Has anyone done this?  Perhaps there should be an example of such a thing in the docs.

**Comment by jhollingworth** [comment]
HttpStateSource just uses the [fetch API](https://fetch.spec.whatwg.org/#fetch-api) so I think you will be able to do:

```js
var FooStateSource = Marty.createStateSource({
  type: 'http',
  getFoo: function () {
    return this.get({ url: 'http://whatever.com/foos', cors: true })
  }
});
```
