### ISSUE TITLE
Obtuse error messages when action causes an error in a store's handler

### ISSUE THREAD

**Issue by optilude** [jhollingworth/marty#128]
If an action triggers a store handler which contains an error (raises an exception), it's all too common to see this obtuse error message in the console (Chrome):

`DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.`

The stack trace is not helpful in identifying where the problem occurs. This makes it quite hard to debug any such errors!

**Comment by jhollingworth** [comment]
Hey, [this bug](https://github.com/jhollingworth/marty/issues/109) was fixed yesterday.

If you update to v0.8.11 the problem should be resolved. Also, if you have [Marty Developer Tools](https://chrome.google.com/webstore/detail/marty-developer-tools/fifcikknnbggajppebgolpkaambnkpae) installed, you should update to v0.8.11 as well.

**Comment by optilude** [comment]
That's great service - fixing the defect the day before I raise it ;) Thanks!

**Comment by jhollingworth** [comment]
no problem, happy to help :smile:
