### ISSUE TITLE
Fetch api compatibility

### ISSUE THREAD

**Issue by adamschoenemann** [jhollingworth/marty#133]
Fetch does not work as expected in Chrome Canary, where fetch is a native implementation. My main issue was with the http source, in the `getHeader` function, there is a use of headers.map which appears to be non-standard, or at least not implemented in Chrome Canary nor original fetch polyfill (as far as I can see). Using the `Headers.get()` method instead should fix this issue

**Comment by jhollingworth** [comment]
hey, thanks for pointing this out. I will get a fix out asap

**Comment by adamschoenemann** [comment]
Thanks! :+1:

**Comment by jhollingworth** [comment]
This is fixed in v0.9 which should be out soon

**Comment by vid** [comment]
I'm finding code which worked prior to the latest Canary now doesn't work. Just wondering if you'll be releasing v0.9 very soon or if I should try to find a workaround. thanks!

**Comment by jhollingworth** [comment]
I can do a hotfix on the v0.8 branch if this is an issue

**Comment by vid** [comment]
If this is a known problem then that would be really helpful. My code only broke since updating Chrome.

**Comment by jhollingworth** [comment]
Hey, [Marty v0.8.13](https://github.com/jhollingworth/marty/blob/master/HISTORY.md#0813--2015-03-03) is out which has the fix for this bug.

**Comment by vid** [comment]
thanks for that. I haven't been able to fully test it due to another issue but on first glance it fixes the problem.  one little issue is I had to manually install babel from the marty directory.

**Comment by jhollingworth** [comment]
Hmm, that shouldn't be needed. I think babelify leaked in from the v0.9 release. I will switch that back now.

Thanks

**Comment by jhollingworth** [comment]
This is fixed in v0.8.14

Thanks

**Comment by vid** [comment]
I had to manually install reactify as well. (=

**Comment by jhollingworth** [comment]
should be fixed now. Sorry about this

On 5 March 2015 at 17:20, David H. Mason <notifications@github.com> wrote:

> I had to manually install reactify as well. (=
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhollingworth/marty/issues/133#issuecomment-77407269>.
>



-- 
http://twitter.com/jhollingworth | http://github.com/jhollingworth |
http://linkedin.com/in/jhollingworth | +44 7866 843 864
