### ISSUE TITLE
Should handlers support an array of constants?

### ISSUE THREAD

**Issue by Rodeoclash** [jhollingworth/marty#135]
Take:

```
handlers: {
  signIn: Constants.SESSION_SIGN_IN,
  _set: [Constants.REGISTRATION_CREATED, Constants.SESSION_SIGNED_IN]
}
```

I have a store handler that I would like to respond to two different actions. Either the user creates a new registration or they signed in. Either result returns a payload containing data about the current user and should be set in the session store.

My natural reaction was to use an array here but it looks like that is not supported. Instead, should you always create one handler per constant?

**Comment by jhollingworth** [comment]
Hey, sorry probably not clear enough in the docs but [arrays of action predicates are supported](http://martyjs.org/api/stores/#action-predicates) :smile:
