### ISSUE TITLE
Static store functions?

### ISSUE THREAD

**Issue by adbl** [jhollingworth/marty#148]
Any plans to support static functions that can be called on the store?

The use case I'm dealing with currently is logic for converting backend data to a more client friendly format directly in the StateSource before dispatching. I would like to implement this code within the responsible Store but I don't want access to `this`.

**Comment by jhollingworth** [comment]
Hey, not sure what you mean. Stores are already statics so everything on it should be accessible globally. 

From what you've said, creating some [utils](https://github.com/jhollingworth/marty-chat-example/blob/master/app/utils/roomUtils.js) might be more appropriate?
