### ISSUE TITLE
Versioned and searchable docs

### ISSUE THREAD

**Issue by dariocravero** [jhollingworth/marty#156]
Hi @jhollingworth, I think it would be worth it if we would keep the docs for each version on the site and one that reflects the latest docs (whatever is on master now) and also have the docs searchable (even Google indexing would probably do here for now)? Thoughts?

**Comment by jhollingworth** [comment]
Yeah, good idea. Will add it to the to do list

**Comment by jhollingworth** [comment]
Available at ``http://martyjs.org/v/{version}``, e.g. http://martyjs.org/v/0.9.0-rc2/
