### ISSUE TITLE
Using {Action Type}_FAILED

### ISSUE THREAD

**Issue by mickhansen** [jhollingworth/marty#157]
http://martyjs.org/guides/action-creators/index.html refers to `{Action Type}_FAILED` and similar types.
Reading the description it seems these default actions could be used to (more) easily implement progress and error tracking - However the payload of these actions seem to only contain an internal actionId generated by Marty.js which can't really be used to reference anything.

Am i going about this the wrong way? I would assume the payloads to contain the same thing as payload or similiar - Would it better to manually dispatch error events from the state source to the source action creators?

**Comment by msimulcik** [comment]
I'd also like to know more about purpose of these automatically dispatched actions that do not carry any application relevant data.

**Comment by jhollingworth** [comment]
hey, sorry for the delay in getting back to you on this. [According to the code we do pass the error as one of the arguments](https://github.com/jhollingworth/marty/blob/master/lib/actionCreators.js#L159-L161) however there might be a bug there. I will have a look at this over the weekend. I'm not [entirely happy with how error handling works right now](https://github.com/jhollingworth/marty/issues/152#issuecomment-76596430) and I think its probably something I'm going to fix in the up coming release. For now I'd say it probably makes more sense to handle errors yourself as I will probably move back to that approach

**Comment by mickhansen** [comment]
@jhollingworth It does contain that, but no reference to the original action, hence no way to map errors/successes back to initial requests.

But i will go forward with handling it manually with sourceActionCreators and the state sources.

Thank you for a great project, made it much easier to get started with Flux

**Comment by jhollingworth** [comment]
@mickhansen Hopefully #163 will resolve your issues

**Comment by mickhansen** [comment]
@jhollingworth Yeah looks like it :)
