### ISSUE TITLE
ES6 arrow syntax in Stores

### ISSUE THREAD

**Issue by dariocravero** [jhollingworth/marty#158]
```
let Store = Marty.createStore({
  getInitialState: function() {
    return {
      foo: 'bar'
    };
  },
  
  getFoo: () => this.state.foo
});

console.log(Store.getFoo()); #=> "Uncaught TypeError: Cannot read property 'state' of undefined"
````

Am I missing something or we can't use the _ES6 arrow syntax_ in stores (in the same way that we can't do it with action creators)?

If so, should we add this warning to the docs as well?
```
Warning! Please avoid using es6 arrow syntax for your callbacks since they are bound to the current context.
```

**Comment by jhollingworth** [comment]
Arrow functions wouldn't really make any sense here since its binding the functions context to ``this`` which is likely undefined or Window

```js
"use strict"
console.log(this)  // undefined

var Store = Marty.createStore({
  getInitialState: function() {
    return {
      foo: 'bar'
    };
  },
  getFoo: (function () { return this.state.foo; }).bind(this)
});
```

**Comment by dariocravero** [comment]
Yes, I know. It was just for the syntactic sugar it provides :). That's why I suggest that we add the warning to the docs as well, should I submit a PR? A funny note: `this` points to the store on Chrome dev tools debugger :/

**Comment by hasdavidc** [comment]
This is more of an EcmaScript thing, so I'm not sure it should be stated in the Marty docs. For a fat arrow, ```this``` is bound to the current context at the time of creation - if tried to use as above in the storeObject, it doesn't realize that it's inside a storeObject and that that should be the ```this```

The same sort of behavior exists within React.createClass (where attempting to use fat arrows causes issues because you've re-bound ```this```).

**Comment by dariocravero** [comment]
@hasdavidc true, it is already there in the action creators guide though, that's why I brought it up

**Comment by jhollingworth** [comment]
That was a slightly special case due to having invokable constants. Now thats been depreciated (#93) so I've [removed that warning from the docs](https://github.com/jhollingworth/marty/pull/137/files#diff-4ce825ab139440a4965263d5c8684a24L19)

**Comment by dariocravero** [comment]
Oh, alright. I see, thanks for the explanation :)
