### ISSUE TITLE
Accept request header for json

### ISSUE THREAD

**Issue by bigardone** [jhollingworth/marty#161]
Hi!
I'm using Marty in a Rails application and I have noticed that all requests done by my HttpStores are done as **"* / *"** instead of being **"application/json"** which is the format that I need. To do so using jquery for example I can set the **dataType: 'json'** attribute and I was wondering if something similar could be done in Marty.

This is what request format looks like using jquery ajax:

```ruby
<Mime::Type:0x007f8d74b18240 @synonyms=["text/x-json", "application/jsonrequest"], @symbol=:json, @string="application/json">
````
And this is using Marty's HttpStore:

```ruby
<Mime::Type:0x007f8d789191c0 @synonyms=[], @symbol=nil, @string="*/*">
```

Thanks in advance and thanks also for the awesome work you're doing here :)

**Comment by jhollingworth** [comment]
could you give me an example of how you're making the http request? If you pass in an object for the body then Marty should [automatically add the ``application/json`` header](https://github.com/jhollingworth/marty/blob/master/lib/stateSources/http.js#L23-L24).

**Comment by bigardone** [comment]
This is how I do it:

```coffee
CollectionsAPI = Marty.createStateSource
  type: 'http'

  findAll: ->
    @get(Routes.collections_path()).then (res)->
      CollectionsSourceActionCreators.receiveItems res.body

**Comment by jhollingworth** [comment]
ah, I see. yeah ``dataType: 'json'`` would be really helpful here. I will add it to v0.9 (hopefully will be out in a week or two). In the meantime you will have do to 

```
CollectionsAPI = Marty.createStateSource
  type: 'http'

  findAll: ->
    request =
       url: Routes.collections_path()
       headers: { 'content-type': 'application/json' }

    @get(request).then (res)->
      CollectionsSourceActionCreators.receiveItems res.body
```

**Comment by bigardone** [comment]
Awesome! thank you very much!

**Comment by jhollingworth** [comment]
dataType is now in the v0.9 branch (#176). Hopefully this will be out soon

Also I realised my previous example was wrong. It should be

```coffeescript
CollectionsAPI = Marty.createStateSource
  type: 'http'

  findAll: ->
    request =
       url: Routes.collections_path()
       headers: { 'Accept': 'application/json' }

    @get(request).then (res)->
      CollectionsSourceActionCreators.receiveItems res.body
```

**Comment by bigardone** [comment]
With the ```headers: { 'Accept': 'application/json' }``` option works like a charm, thanks!
