### ISSUE TITLE
Simplify error handling

### ISSUE THREAD

**Issue by jhollingworth** [jhollingworth/marty#163]
How action creators work, in particular error handling is a recurring issue (#157, #152, #127) we need to solve. Having the action creators automatically dispatch ``ACTION_{type}`` errors seemed like a neat idea at the time but it's not very useful and has lead to a load of complicated code and crappy APIs.

I think we should just go back to a simpler, explicit approach ([Yahoo has some good examples](https://github.com/yahoo/flux-examples/blob/master/chat/actions/createMessage.js)):

* No more dispatching ``ACTION_{type}`` errors
* Don't wrap action creator functions in promises
* Explicit error handling

```js
var FooActionCreators = Marty.createActionCreators({
  createFoo(foo) {
    this.dispatch(Constants.RECIEVE_FOO, foo);

    FooAPI.createFoo(foo).catch((error) => {
      this.dispatch(Constants.RECIEVE_FOO_FAILED, foo, error);
    });
  }  
});
```

As much as I'd like to have some [automatic error handling/retrying](http://ianobermiller.com/blog/2014/09/15/react-and-flux-interview/) I think we should get the simple case right first.

**Comment by jhollingworth** [comment]
@oliverwoodings @dariocravero what do you think?

**Comment by dariocravero** [comment]
:+1: for a simplified approach. Clean stack traces are vital and even though we have some tracing right now the confusion it creates as to what actually originated the exception is enough to rethink what Marty is doing here.
Eventually the automated functionality could be provided through some syntactic sugar at some stage?

**Comment by jhollingworth** [comment]
#166 should resolve this
