### ISSUE TITLE
Expose Store#handleAction

### ISSUE THREAD

**Issue by jhollingworth** [jhollingworth/marty#164]
Now that ES6 classes make using object hashes a pain I'm re-evaluating how we use them. Thanks to #163 we're getting rid of object hashes in Action Creators so I'm wondering if it would make sense to get rid of them in the store as well? If we got rid of the handlers object hash replacing it with a switch case we'd be able to do everything you can do with [action predicates](http://martyjs.org/api/stores/index.html#action-predicates) but with the added benefits that:

* We wouldn't have to expose action handlers to the public interface
* You can express more complicated scenarios
* The code would be terser and action types would be next to the actual code rather than having the handlers object in a different place from the actual handlers
* Our code would be much simpler
* [Potential performance benefits](https://twitter.com/fisherwebdev/status/557980069440651265)

```js
var FooStore = Marty.createStore({
  getFoo(id) {
    return this.state.foos[id];
  }
  handleAction(action) {
    switch(action.type) {
      case Constants.RECIEVE_FOO:
        var foo = action.payload.foo;
        this.state.foos[foo.id] = foo;
        this.hasChanged();
        break;
      case Constants.RECIEVE_FOO_FAILED:
        var { foo, error } = action.payload;

        this.state.errors[foo.id] = error;
        this.hasChanged();
        break;
    }
  }
})
```

I reckon we should keep the old style for now but add a warning saying it will be depreciated in v0.10.

**Comment by jhollingworth** [comment]
@oliverwoodings @dariocravero @giuse88 what do you think?

**Comment by Dakuan** [comment]
Not sure - sorry. That code is going to sprawl and could be bug prone (accidental missing `break`), I much prefer having declarative stuff right at the top stating what actions are handled where, with the implementation below. A massive switch statement would be a step back IMO

**Comment by dariocravero** [comment]
Agree with @Dakuan, a big switch statement makes it harder to reason in the long run.

**Comment by Dakuan** [comment]
would something in the constructor be a reasonable compromise? E.g something like the `this.bindActions` here: http://fluxxor.com/documentation/stores.html#-fluxxor-createstore-spec-

**Comment by jhollingworth** [comment]
That approach still means your action handlers are publicly exposed + constants aren't co-located with its associated code.

This example from [NuclearMail](https://github.com/ianobermiller/nuclearmail/blob/master/src/js/MessageStore.js) is a good example of how it would scale to a large store. I guess it does get a little unwieldy...

**Comment by jhollingworth** [comment]
On the other hand (and I know this is probably not the greatest argument in the world) this is the approach Facebook have taken for all their Flux code. It's obviously scaled very well for them so can't be all that bad

**Comment by dariocravero** [comment]
Mmm, that's true. You have a point with those methods not being publicly available being a good thing. handleAction is publicly available is sort of the same as someone

On NuclearMail's example they do use some sort of ["private method convention"](https://github.com/ianobermiller/nuclearmail/blob/master/src/js/MessageStore.js#L39-L42). Alternatively, this could also be enforced as a pattern:

```
function receiveFoo(payload) {
  var foo = action.payload.foo;
  this.state.foos[foo.id] = foo;
  this.hasChanged();
}

function receivedFooFailed(payload) {
  var { foo, error } = payload;
  this.state.errors[foo.id] = error;
  this.hasChanged();
}

class FooStore extends Marty.Store {
  getFoo(id) {
    return this.state.foos[id];
  }
  handleAction(action) {
    switch(action.type) {
      case Constants.RECIEVE_FOO:
        receiveFoo.bind(this)(action.payload);
        break;
      case Constants.RECIEVE_FOO_FAILED:
        receivedFooFailed.bind(this)(action.payload);
        break;
    }
  }
}
```

Then it's up to whomever builds the application to use that pattern.

Alternatively, we could hide that action handler?

```

function handleAction(action) {
  switch(action.type) {
    case Constants.RECIEVE_FOO:
      receiveFoo.bind(this)(action.payload);
      break;
    case Constants.RECIEVE_FOO_FAILED:
      receivedFooFailed.bind(this)(action.payload);
      break;
  }
}

class FooStore extends Marty.Store {
  constructor(options) {
    super(_.extend(options, {actionHandler: handleAction});
  }
  getFoo(id) {
    return this.state.foos[id];
  }
}
```

Thoughts?

**Comment by oliverwoodings** [comment]
What about a function called getActionHandlers that is responsible for returning an object of constants and handlers?

**Comment by jhollingworth** [comment]
@oliverwoodings  its less so the fact we expose the ``handlers`` object hash and more that 

1. We're exposing private functions publicly
2. The place you define the action type is far away from the actual handler so you've got to do some mental processing of the file
3. Action predicates limit you how you handle actions. If you have a function you can do whatever you want

**Comment by jhollingworth** [comment]
@dariocravero I much prefer your first example

I agree that handleAction would be public but I you could argue its a much smaller surface area

**Comment by jhollingworth** [comment]
Just been debating this with a colleague. Here are the two styles side by side. Still undecided but if people are really anti it then happy to keep as is

**handlers**

```js
class FooStore extends Marty.Store {
  get handlers() {
    return {
      recieveFoo: Constants.RECIEVE_FOO,
      recieveFooFailed: Constants.RECIEVE_FOO_FAILED
    }
  }
  recieveFoo(foo) {
    this.state.foos[foo.id] = foo;
    this.hasChanged();
  }
  recieveFooFailed(foo, err) {
    this.state.errors[foo.id] = error;
    this.hasChanged();
  }
}
```

**switch**

```js
class FooStore extends Marty.Store {
  handleAction(action) {
    var { foo, error } = action.payload;
    switch(action.type) {
      case Constants.RECIEVE_FOO:
        this.state.foos[foo.id] = foo;
        this.hasChanged();
        break;
      case Constants.RECIEVE_FOO_FAILED:
        this.state.errors[foo.id] = error;
        this.hasChanged();
        break;
    }
  }
}
```

**Comment by dariocravero** [comment]
@jhollingworth looking at [one of Facebook's Flux examples](https://github.com/facebook/flux/blob/master/examples/flux-chat/js/stores/MessageStore.js#L96-L127) a bit closer it actually looks more like my second example as in that they pretty much don't make those handlers public at all and `dispatchToken` is explicitly set with those handlers.

What about repurposing `Marty.register(Store)` to set that list then That would also simplify [handleAction](https://github.com/jhollingworth/marty/blob/d1a17235a5abc6b9c553bc81b04603a10edfb5f7/lib/store.js#L360-L403) considerably I guess.

So it could actually look a bit like:

```javascript
class FooStore extends Marty.Store {
  getFoo(id) {
    return this.state.foos[id];
  }
}

Marty.register(FooStore,  function handleAction(action) {
  switch(action.type) {
    case Constants.RECIEVE_FOO:
      receiveFoo.bind(this)(action.payload);
      break;
    case Constants.RECIEVE_FOO_FAILED:
      receivedFooFailed.bind(this)(action.payload);
      break;
  }
})
```

**Comment by jhollingworth** [comment]
I like that its separate but would like to keep ``Marty.register`` focused on type registration

I think its best to keep the old style as it a) works b) would mean asking users to update their code for arguable value.

**Comment by dariocravero** [comment]
Cool
