### ISSUE TITLE
Marty.Component doesn't work in IE <=10 

### ISSUE THREAD

**Issue by jhollingworth** [jhollingworth/marty#171]
[You cannot inherit static properties with IE <= 10](https://babeljs.io/docs/usage/caveats/#classes-10-and-below-) which means you can't inherit ``contextTypes`` thus ``martyContext`` isn't passed down

**Comment by jhollingworth** [comment]
Looks like the only way is to do ``Component.contextTypes = Marty.Component.contextTypes`` or ``Component.contextTypes = { marty: null }``.

**Comment by SimonErich** [comment]
Hi James, thank you so much for this amazing starterpack. It helped me a lot to understand React and Flux.
But one big thing for me is the support.
Is there a way to make it work in IE <= 10 using polyfills or is this not planned at all?

**Comment by oliverwoodings** [comment]
@SimonErich just don't use ES6 classes and you don't need to use Marty.Component

**Comment by jhollingworth** [comment]
@SimonErich turns out this doesn't actually matter. The only time you need access to the context is when rendering on the server which is in node.js (thus inheriting contextTypes works). 

Even if this wasn't the case, all you'd have to do is explicitly set the contexTypes of the inherited component e.g. ``SomeComponent.contextTypes = Marty.Component.contextTypes``
