### ISSUE TITLE
Work out why you need to resolve state sources

### ISSUE THREAD

**Issue by jhollingworth** [jhollingworth/marty#185]

**Comment by FoxxMD** [comment]
What do you mean by this?

**Comment by jhollingworth** [comment]
Sorry, bit confusing if don't know features in v0.9.

To support isomorphisim [we've built a mechanism for resolving instances for specific context (``.for(this)``)](https://github.com/jhollingworth/marty-chat-example/blob/v0.9/app/queries/roomQueries.js#L15). This is needed when you're using ActionCreators, Stores and Queries (new in v0.9) however not needed for state sources. For some reason though if I don't resolve the state source it behaves weirdly. This is just a reminder to work out whey
