### ISSUE TITLE
Action predicates and action status emitters

### ISSUE THREAD

**Issue by FoxxMD** [jhollingworth/marty#189]
I want to have my store change state based on whether an action has been dispatched to help me control my UI state.

I know I can use [these additional action types](http://martyjs.org/guides/action-creators/index.html) but I was wondering if there's a way for the action handler in my store to know what action has been dispatched?

My main concern is that I will would have to write separate handlers for each action state I wanted to listen to in order to change the part of the state for the UI associated with that action. What I'd rather do is write one handler that listens to multiple actions and then identify which action has been dispatched so I can change the appropriate state.

EX

Currently

```
//Action creator
Action.getReport();

//In store
handlers:{
        updateUIStateForGetReportOnStart: constants.GET_REPORT_START,
        updateUIStateForGetReportOnDone constants.GET_REPORT_DONE
},
updateUIStateForGetReportOnStart: function(){
    this.state['reportLoading'] = true;
},
updateUIStateForGetReportOnDone: function(){
    this.state['reportLoading'] = false;
},
...
```

What I'd like to do

```
//Action creator
Action.getReport();

//In store
handlers:{
        updateUIStateForGetReport: [constants.GET_REPORT_START,constants.GET_REPORT_DONE,
constants.GET_ANOTHER_REPORT_START, constants.GET_ANOTHER_REPORT_DONE]
},
updateUIStateForGetReport: function(actionType){
    switch(actionType){
        case 'GET_REPORT_START':
            this.state['reportLoading'] = true;
        case 'GET_REPORT_DONE':
            this.state['reportLoading'] = false;
            break;
        case 'GET_ANOTHER_REPORT_START':
            this.state['anotherReportLoading'] = true;
            break;
        case 'GET_ANOTHER_REPORT_DONE':
            this.state['anotherReportLoading'] = false;
            break;
    }
},
```

Additionally I was hoping you could expand a little more about what the "source" property in the action is, seen [here](http://martyjs.org/api/stores/#action-predicates)? 

Thanks!

**Comment by jhollingworth** [comment]
``this.action`` is available in the action handler

```js
someAction(foo, bar) {
   console.log(this.action.type) //SOME_ACTION
}
```

Ignore [those action types](http://martyjs.org/guides/action-creators/index.html) and the "source" property are going away in v0.9 because they're not very useful.

**Comment by FoxxMD** [comment]
Fantastic! `this.action.type`is exactly what I needed. Thanks
