### ISSUE TITLE
Pattern change in htmlSource fetch

### ISSUE THREAD

**Issue by wreppun** [jhollingworth/marty#190]
previously, and as currently documented, the pattern for fetching went something like:
```javascript
Marty.createStateSource({
  type: 'http',
  getStuff: function() {
    return this.get('/api/stuff/').then(function(res) {
      actOn(res.body);
    });
  }
});
```
I haven't dug into where the underlying changes occurred, but the new pattern looks something like:
```javascript
Marty.createStateSource({
  type: 'http',
  getStuff: function() {
    return this.get('/api/stuff/')
      .then(function(res) {
        return res.text(); // returns a promise
      })
      .then(function(promisedText) {
        actOn(promisedText);
      });
  }
});
```
This happens with:
`marty@0.8.15`
`isomorphic-fetch@1.6.0`
`xmlhttprequest@1.7.0`

Maybe this is handled in `0.9.x` (haven't checked), but thought I'd at least document it here.

**Comment by jhollingworth** [comment]
Hey, 

``Result#text()`` and ``Result#json()`` are APIs that come from [fetch](https://github.com/github/fetch). Personally I'm not a massive fan so, if the response content type is application/json, we will [automatically do the ``.json()`` but for you and add it as a body property](https://github.com/jhollingworth/marty/blob/master/lib/stateSources/http.js#L32-L38). 

I realise this isn't too everyones taste so in v0.9 I introduced [hooks](https://github.com/jhollingworth/marty/blob/v0.9/docs/_api/state-sources/http.md#hooks) which allow you to modify requests before they are sent and responses. I've moved the logic for populating the body into a [hook](https://github.com/jhollingworth/marty/blob/v0.9/lib/stateSource/inbuilt/http/hooks/parseJSON.js) so you can remove/replace it if you want

Thanks
James
