### ISSUE TITLE
Isomorphic questions/problems

### ISSUE THREAD

**Issue by jhollingworth** [jhollingworth/marty#193]
* What happens if a request is in process on the server? Do we need to restart requests?
* Socket.io source doesn't work in Chat example
* Getting ``Failed to render /rooms/d7175740-c8e3-11e4-8916-079321b67708 [TypeError: Cannot read property 'result' of undefined]`` errors in Chat example

**Comment by oliverwoodings** [comment]
What if we created a socket.io channel mounted on the express server that automatically pipes through the results of any pending requests?

**Comment by jhollingworth** [comment]
that would be seriously cool!
