### ISSUE TITLE
Prevent raw JSON when using browser's back button

### ISSUE THREAD

**Issue by bigardone** [jhollingworth/marty#196]
Hi!
I'm developing a Rails app and I've found some cases where  a user clicks the back button and the browser renders the last request as raw JSON. This seems to be because the browser serves the last cached response for a certain URL so if the user visits ```/collections``` and the app serves a collections page where it renders a **CollectionList** React component which uses that uses a **HTTP state source** which retrieves the data from the same URL but as JSON then when clicking into a collection to see it's details and then going back to the list by clicking the browser's back button the raw JSON will be displayed.
I've seen that this can be prevented in jQuery by setting the **cache** param to false when doing ajax requests (http://api.jquery.com/jQuery.ajax/) and I was wondering if this could be done in Marty too. 
Another solution I can implement is to separate all the JSON requests to a different API controller but I wanted first to share this with you to see if adding something like a **cache: false** to Marty would work :)
Thanks in advance!

**Comment by oliverwoodings** [comment]
How do you differentiate between serving JSON from that URL and rendering a
component at that URL? To be honest this doesn't sound like an issue with
marty - a URL should always return the same 'resource', therefore you
shouldn't serve two very different types of content from the same one.

**Comment by bigardone** [comment]
Yep, you're right. A Rails controller may serve different responses depending on the request type. So if the request type is ```text/html``` it serves a html view, but if the request type is ```application/json``` it can also serve JSON, but at the end is the same URL. I think you're right and maybe disabling caching won't work either as it will only show the HTML but the JSON will not as is not being cached. 
I think I'm going to create new controllers for this.
Thanks!
