### ISSUE TITLE
State mixin and ImmutableJS

### ISSUE THREAD

**Issue by Rodeoclash** [jhollingworth/marty#200]
This is a general architecture question but how are others handling using ImmutableJS with Marty (and in particular, the state mixin).

One of the benefits of ImmutableJS is the ability to easily compare equality between objects created using it. This would encourage creating state mixins which reference the ImmutableJS objects kept within the stores, e.g:

```
var WatchState = Marty.createStateMixin({
  listenTo: [PositionStore],
  getState: function () {
    return {
      position: PositionStore.state,
    };
  }
});
```

The downside I have is that I like to build methods on the store that encapsulate the state object and perform operations on it. A very simple example would be getting the last item out of the store. I often have methods in my stores similar to:

```
 currentPosition: function () {
   return this.state.last();
 }
```

Generally my methods aren't this simple and instead usually consist of maps, filters etc.

The problem with this is that the state mixin returns the ImmutableJS object when what I really want is the store itself. However, if I watch the store, I don't get a refresh when the state it encapsulates changes. How are others handling this? Do you simply watch the state but reference the store directly through it's "require" include? Or is their something I'm missing with the use of MartyJS and ImmutableJS together?

**Comment by jhollingworth** [comment]
Hey, this is how we tend to use stores with immutable

```js
var FooStore = Marty.createStore({
  getInitialState() {
    return Immutable.List();
  },
  getNewFoos() {
    return this.state.filter(foo => !foo.get('new'));
  }
});


var FooState = Marty.createStateMixin({
  listenTo: FooState,
  getState() {
    return {
      foos: FooStore.getNewFoos()
    }
  }
});


var NewFoos = React.createClass({
  mixins: [FooState],
  render() {
    return (
      <div className="new-foos">
        {this.state.foos.map(foo => <Foo foo={foo} />).toArray()}
      </div>
    )
  }
})
```

**Comment by jhollingworth** [comment]
We never reference Store.state directly, we call functions on the store which internally use ``this.state``

**Comment by Rodeoclash** [comment]
Awesome thanks!
