### ISSUE TITLE
Error in done handler is caught and sent to failed handler 

### ISSUE THREAD

**Issue by adbl** [jhollingworth/marty#201]
I am seeing the following behavior when crashing in `done` handler of `fetch.when`:

```
var component = user.when({
  pending: ...,
  done: function (user) {
    this.will.crash();
    return <div className="user">{user.name}</div>;
  },
  failed: function (error) {
    console.log(error); // => TypeError: Cannot read property 'crash' of undefined ...
    // this.will.also.crash();
    ...
  }
});
```

Is this intentional? I am having trouble debugging render crashes in "conditional" components (that get rendered when the promise is fulfilled). The exception in `done` handler is caught and presented to `failed` handler. It is not rethrown since I'm unable to see this exception in my state source code which triggers new actions => state updates => rerender.

An interesting observation is that if I crash in the `failed` handler (the outcommented line above) I see the following output in console:

```
An error occured when handling the DONE state of the fetch 'blaha-3' from the store X
  TypeError {stack: (...), message: "Cannot read property 'also' of undefined"}
  (stack trace...)
```
In this case it looks like the error propagates and is presented to the console, which I believe is preferable also in the case of crashing `done` handler.

**Comment by jhollingworth** [comment]
This is a manifestation of a more fundamental problem with Marty's automatic error handling in actions. That logging was [introduced as an attempt to make this stuff simpler](https://github.com/jhollingworth/marty/issues/127) however it only alleviated the problem. 

Automatic error handling has been completely removed in [Marty v0.9](http://martyjs.org/v/0.9.0-rc2/guides/action-creators/migrating-from-v8.html) which has made debugging these issues significantly easier. Marty v0.9 is essentially done from a code perspective so doing the upgrade should make debugging much easier

**Comment by adbl** [comment]
Ok! We will then test the current RC out...
