### ISSUE TITLE
Scrap Marty.Component in favour of Marty.createContainer

### ISSUE THREAD

**Issue by jhollingworth** [jhollingworth/marty#204]
FB just blogged about how [Relay works](http://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html).

This makes a lot of sense and gets around a load of the issues with ``Marty.Component`` (e.g. contextTypes, having to inherit from a base class). 

I suggest we scrap ``Marty.Component`` altogether and just replicate ``Relay.createContainer``

```js
class User extends React.Component {
  render() {
    return this.props.user.when({
       ...
    });
  }  
}

module.exports = Marty.createContainer(User, {
  listenTo: UserStore,
  user() {
    return UserStore.getUser(123)
  }
});
```

**Comment by bigardone** [comment]
So this means that:

- Components will use props received from containers instead of state.
- Stores state changes will affect containers.
- State mixins are not longer needed.

Is this right?

**Comment by jhollingworth** [comment]
Yeah, spot on. It provides a clear separation with between the component and fetching state (no more ``when`` in you're components) plus opens some more complex scenarios (e.g. only certain properties are needed before rendering, setting default values when pending, etc). 

The [PR](https://github.com/jhollingworth/marty/pull/206) has an expanded example of how its going to look.

**Comment by jhollingworth** [comment]
Although, I should say state mixins aren't being depreciated just yet (maybe v0.11). We're just recommending you use containers as they are better.

**Comment by bigardone** [comment]
Awesome, it looks really useful.
