### ISSUE TITLE
cannot find module 'react-router/build/npm'

### ISSUE THREAD

**Issue by SimonErich** [jhollingworth/marty#220]
Hi,

I just tried to install the new martyjs on 2 different ubuntu 14.04 and 14.10 computers, but when I run "npm start" I always get the error above:

       $ npm start
	> herz@0.0.0 start /var/www/herz
	> grunt

	Running "concurrent:serve" (concurrent) task
	Running "browserify:watch" (browserify) task
	Running "nodemon:serve" (nodemon) task
	[nodemon] v1.2.1
	[nodemon] to restart at any time, enter `rs`
	[nodemon] watching: *.*
	[nodemon] starting `node ./bin/www`

	module.js:340
	    throw err;
		  ^
	Error: Cannot find module 'react-router/build/npm'
	    at Function.Module._resolveFilename (module.js:338:15)
	    at Function.Module._load (module.js:280:25)
	    at Module.require (module.js:364:17)
	    at require (module.js:380:17)
	    at Object.<anonymous> (/var/www/herz/node_modules/marty-express/index.js:2:14)
	    at Module._compile (module.js:456:26)
	    at Module._extensions..js (module.js:474:10)
	    at Object.require.extensions.(anonymous function) [as .js] (/var/www/herz/node_modules/babel/lib/babel/api/register/node.js:130:7)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	[nodemon] app crashed - waiting for file changes before starting...
	>> Watchifying...

**Comment by jhollingworth** [comment]
Hey, can you check which version of marty-express you are using?

**Comment by jhollingworth** [comment]
Also, try running ``npm update marty-express``

**Comment by SimonErich** [comment]
Hey James,

the marty-express version is 0.1.0
(here is my npm list output)
https://gist.github.com/SimonErich/8c664e69b0925f8366de

One of the systems is a vanilla ubuntu. I just installed it today and the only thing I installed so far was npm to test marty on there.

**Comment by jhollingworth** [comment]
Can you update to the latest version of marty-express (0.2.0). That should fix it :)

**Comment by SimonErich** [comment]
Hi James,
thanks. That was it. I tried updating it before, but it wouldn't work.
I updated the package.json now and added the 0.2.0 and now it's working perfectly fine.

But it's strange. I installed marty line by line as described in the guides, but got 0.1.0 in the package.json.

Thank you.

**Comment by jhollingworth** [comment]
Hmm, that is odd. I updated the yeoman generator so that the minimum version it will accept is 0.2.0 so hopefully this won't happen in the future.

Thanks for being patience with this :)
