### ISSUE TITLE
Exposing other methods on components wrapped in containers

### ISSUE THREAD

**Issue by taion** [jhollingworth/marty#224]
The current implementation of containers does not expose any methods on the wrapped components. This means that I can't access public methods on those wrapped components (e.g. via a `ref` on the owner of that component).

Can we transparently proxy all public methods on the wrapped component?

**Comment by jhollingworth** [comment]
hmm, good question! My concern with proxying requests is that you could easily forget about the proxying and think its the inner component. How about if I exposed the inner component (e.g. ``container.getInnerComponent()`` or ``container.innerComponent``?

**Comment by dariocravero** [comment]
@taion do you have a use case for that?

Are you trying to access the rendered element's method from within the rendered container or are you trying to get a hold of the component itself? [The latter seems to be implemented already](https://github.com/jhollingworth/marty/blob/master/lib/createContainer/createContainer.js#L91).

**Comment by taion** [comment]
@jhollingworth 

I can see the merits both ways. The real answer would be to do whatever FB do, but they haven't said yet. From an ergonomic perspective I'd rather not do `getInnerComponent()` (and I think having to do something like this is one of the major downsides of the composition-over-mixin argument). What do you think of adding an extra argument to `createContainer` that explicitly lists public methods to proxy over?

@dariocravero 

That looks like it's actually the class of the contained component, not the component itself.

**Comment by jhollingworth** [comment]
Agree on doing what FB does, hopefully they will discuss in F8.

What are you're use cases for this? Is it for testing?

**Comment by taion** [comment]
I have a component that serves as an uncontrolled input. I connect it to a store to get some data about the set of appropriate values (e.g. the set of allowed labels, like on GitHub issues). I want to expose a `getValue` method on the component so that its parent can access the values when e.g. submitting the form.

**Comment by dariocravero** [comment]
@taion thanks for clarifying that. A quick note on definitions though: what you're calling the component is actually a react element and the class component is a react component [ref](https://facebook.github.io/react/docs/glossary.html#react-components).

**Comment by jhollingworth** [comment]
I guess we could implement a `proxy` property which proxies functions

```js
Marty.createContainer(User, {
  proxy: ["getValue"]
});
```

My concern with that it's not clear without looking at the documentation what its doing. I'd prefer to be more explicit about it and have something like this:

```
module.exports = Marty.createContainer(User, {
  getValue() {
    return this.getInnerComponent().getValue()
  }
});
```

Would that work for you?

Also, I have no idea about your code base so correct me if I'm wrong but would it not be better to have a 'FormStore' where you keep the current state of the form? We did something very similar a couple of weeks ago and found it worked quite well

**Comment by taion** [comment]
@dariocravero 

My bad.

@jhollingworth 

Both of those would work for me. Might be able to get the best of both worlds with a more explicit name like `proxyMethods` for the former, though.

In my case, I could use a separate store, the component in question is intended to be reusable, so I don't want to tie the value of the component to a particular store. It's pretty much a custom `<select multiple>` that I'm using in a couple of difference places, in multiple different forms, from which I want to be able to call something like `this._input.getValue()`.

Really I'm starting with a standalone component that's not tied into the broader Flux-style framework, and I'm now looking for an easy way to inject a value from a store into the component as e.g. the list of options.

**Comment by taion** [comment]
FWIW React Bootstrap also uses this pattern of exposing public methods like `getValue()` and `getChecked()` to expose the value of its `<Input>` elements: http://react-bootstrap.github.io/components.html#input

In general, since I'm not doing any two-way binding here, I feel like it's just easier and cleaner to treat the input-like element as being uncontrolled, and only pulling the value of the element itself when I need it (i.e. when I want to submit the form).

**Comment by jhollingworth** [comment]
OK cool, I'm going to add the ability to add functions to a container

```js
module.exports = Marty.createContainer(User, {
  getValue() {
    return this.getInnerComponent().getValue()
  }
});
```

Will be in v0.9.3 (hopefully today)
