### ISSUE TITLE
nested routes

### ISSUE THREAD

**Issue by SimonErich** [jhollingworth/marty#231]
Hi,

in marty 0.8 it was possible to change the route definition to the nested style like this:

        var React = require('react');
        var Route = require('react-router').Route;

        var routes = (
          <Route path="/" handler={require('../views/default')}>
              <Route name="home" path="/" handler={require('../views/home')} />

              <Route name="profile" path="/profile/:id" handler={require('../views/profile')} />
          </Route>
        );

      module.exports = Router.create({
             routes: routes,
             location: Router.HistoryLocation
       });

And it worked. I did this to have it more structured and to have a parent layout (views/default) rendered automatically.

But in marty 0.9.0 this doesn't work anymore. I always get an "Internal Server error" on the browser and a       
          Failed to render /profile/1 [Error: must specify an id]
on the console.

I guess it's because of the server rendering. I did add:
          app.get('/api/profile/:id', require('./routes/getProfile'));

to the server/index.js

Is there a way to get this working or how would you recommend to include layout headers and footers?
Just make components and use them in every view?

Thanks

**Comment by jhollingworth** [comment]
Hmm, that "must specify an Id" is interesting. I could be wrong but I have a feeling that's due to you making a fetch in a store without specifying an id

**Comment by SimonErich** [comment]
I actually tried this on fresh install of marty and the only thing I changed was the views/default.js file and used the yo:marty domain generator to create the files for "profiles".
When I just use the following in my routes.js file, everything works again:

        var React = require('react');
        var Route = require('react-router').Route;
        
        module.exports = [
              <Route name="profile" path="/profile/:id" handler={require('../views/profile')} />
        ];

**Comment by SimonErich** [comment]
I actually worked on it today again and you were absolutely right.
The default generator created a profile store and component that needed an id.
I have no idea why it suddenly worked for me, but after debugging it down and removing everything it worked again.
Sorry to bother you and thanks again for your great support.

Is there actually a way to donate something towards you/this project?

You are doing so much work here and not only by offering the code, but also with the documentation and your support, I'm sure a couple of people would love to support your work a little bit.
I mean: we are profiting from it as well :)
