### ISSUE TITLE
Trying to listen to something that isn't a store

### ISSUE THREAD

**Issue by sporto** [jhollingworth/marty#233]
I'm using ES6 and declaring my store like:

```
export default class LibrariesStore extends Marty.Store {
  ...
}
```

Then in my component I import the store and try to use it in a container:

```
import librariesStore from '../../stores/libraries.es6';

export default Marty.createContainer(Main, {
  listenTo: librariesStore,
  ...
})
```

In the browser I see:
```
Warning: Trying to listen to something that isn't a store" function LibrariesStore()
```

So I see I'm importing the LibrariesStore class. But there is no instance created anywhere. So something seems to be missing here, where is the store instance supposed to be instantiated?

**Comment by sporto** [comment]
Oh, found this http://martyjs.org/guides/es6/index.html
Closing

**Comment by SudoPlz** [comment]
The link is dead and I have the same problem... What is the solution?

**Comment by sporto** [comment]
Back in Marty 0.9 you had to register stores before using them:

```
 class LibrariesStore extends Marty.Store {
  ...
}

export default Marty.register(LibrariesStore)
```

Then 

```
import librariesStore from '../../stores/libraries.es6';

export default Marty.createContainer(Main, {
  listenTo: librariesStore,
  ...
})
```

But Marty 0.10 is quite different

**Comment by SudoPlz** [comment]
Thank you... What I was doing wrong is, I had `  listenTo: "librariesStore",` in my code instead of `  listenTo: librariesStore,`. I thought that Marty kept track of our stores and I just had to provide its name (the one I set as its id). I was wrong... Now all seems to work.
