### ISSUE TITLE
latest Dev Tools not showing up

### ISSUE THREAD

**Issue by clearly** [jhollingworth/marty#236]
I had .8 and dev tools were showing up but not totally working well. Just upgraded everything to 0.9.1 and now Dev Tools don't show up at all. Chrome 41.0.2272.101 m. Let me know what other information I can provide.

**Comment by jhollingworth** [comment]
What version of Marty Dev Tools are you using? [Marty Dev Tools v0.9](https://chrome.google.com/webstore/detail/marty-developer-tools/fifcikknnbggajppebgolpkaambnkpae?hl=en) got released the other day which should work with Marty v0.9. If you've still got the older version it won't show up

**Comment by clearly** [comment]
Weird. Nothing changed but started working. Heisenbug.

**Comment by jhollingworth** [comment]
Awesome, I think Chrome app [autoupdates](https://developer.chrome.com/extensions/autoupdate)

Thanks
James
