### ISSUE TITLE
`this.fetch` in store swallows errors

### ISSUE THREAD

**Issue by sporto** [jhollingworth/marty#238]
In my store I had something like

```js
	fetchLibraries(keyword) {
		return this.fetch({
			id: keyword,
			locally: function () {
				...
			},
			remotely: function () {
				return librariesQuery.fetchLibraries(keyword);
			}
		});
	}
```

But in my Query I had:

```
  getLibraries(keyword) {
     ...
```

So `getLibraries` as opposed to `fetchLibraries`.

Browser shows no errors at all, the `failed` callback on `createContainer` gets called. But this is far from desired. Optimally only errors coming from actual fetch later on should be catched.

**Comment by sporto** [comment]
So in https://github.com/jhollingworth/marty/blob/f780507049ca93ceafdb2b13aa0f6164673b255a/dist/node/lib/store/fetch.js#L85

Can this be changed so you only catch specific kind of errors? Let everything else bubble up?

**Comment by jhollingworth** [comment]
Completely agree with you. Thats a hangover from v0.8 where we attempted to handle errors for you. Will remove it
