### ISSUE TITLE
Context and `for` is not clear (to me at least)

### ISSUE THREAD

**Issue by matthewgertner** [jhollingworth/marty#239]
The documentation explains that the different contexts have different instances of the registered objects (e.g. Stores, Action Creators) and that they are needed for isomorphic applications (presumably because the server and browser might have different contexts).

My application is hosted entirely in the browser, so it's not clear to me why I have to worry about the context at all. However, I observed the following. I defined a container like this:

```
module.exports = Marty.createContainer(MyComponent, {
  listenTo: MyStore,
  fetch: {
    someProp() {
      return MyStore.for(this).getSomeProp();
    }
  }
});
```

This behaves as expected: if `someProp` must be retrieved asynchronously by the store, the first call returns a fetch result with the state set to `PENDING`. When the state changes to `DONE`, the value is retrieved and the component is rendered. 

However, if I omit the `for(this)` then the fetch result is returned directly by `getSomeProp`, so I have to check the state myself and retrieve the `result` property manually (i.e. `getSomeProp().result`) when it is available.

What am I missing? Why does `for(this)` need to be used in this case and why does it behave as I described when `for(this)` is omitted?

**Comment by jhollingworth** [comment]
You're right, ``.for(this)`` is only needed when on the server. If you're only working in the browser [then ``for(this)`` is supposed to just return itself](https://github.com/jhollingworth/marty/blob/master/lib/utils/resolve.js#L16) (e.g. ``MyStore.for(this)`` should just return ``MyStore``). However what its supposed to do doesn't always line up to what it is doing so I will do a bit of investigation and get back to you

**Comment by jhollingworth** [comment]
I've just added a couple of tests to check if the behaviour changes when using `.for` but seems in the browser `MyStore.for(this) === MyStore`. Is there anything else special you are doing? Also are you using Marty v0.9.4?

**Comment by matthewgertner** [comment]
Oops, you're right of course. I guess I changed two things at once while trying to get my app to work and wrongly interpreted the result. It would be helpful to have an example of a store with a custom implementation of `fetch` (I'm using it to access a third-party API via a JS wrapper library) since the only examples I could find used existing state sources. Totally my bad but I think I would have figured this out a lot more quickly if it were clearer exactly what the `remotely` method is meant to do (which I now believe is to return a promise, and then set the appropriate state property and resolve the promise once it has retrieve the relevant data).
