### ISSUE TITLE
Clarification: Fetching more data from a View

### ISSUE THREAD

**Issue by StevenLangbroek** [jhollingworth/marty#245]
I'm having a hard time figure out how to instruct the store to fetch more data (paginated data-source) from a Component's "load more data button". Is there a "correct" way of dispatching this?

**Comment by jhollingworth** [comment]
Hey, difficult to say without looking at your code however this is roughly how I've done pagination in the past

```js
class Users extends React.Component {
  render() {
    return <div class="Users">{this.props.users.map(user => <User user={user} />)}
  }
}

module.exports = Marty.createContainer(Users, {
  fetch: {
    users() {
      return UsersStore.getPaginatedUsers({
        skip: this.props.page,
        take: 10
      })
    }
  }
}

... 

<Users page={1} />
```
