### ISSUE TITLE
Container lifecycle events

### ISSUE THREAD

**Issue by taion** [jhollingworth/marty#249]
It would be nice if containers supported passing in `componentDidMount` and `componentWillUnmount`. One pattern that might be nice to use would be something like:

```js
{
  componentWillMount() {
    Store.subscribeItem(this.props.itemId);
  },

  fetch: {
    item() {
      return Store.getItem(this.props.itemId);
    }
  },

  componentWillUnmount() {
    Store.unsubscribeItem(this.props.itemId);
  }
}
```

(Is this right? Or should subscribe/unsubscribe go on the Queries instead of the Store?)

This doesn't have to go on the container, but it'd be nice to consolidate everything on one place. Otherwise, `createContainer` should at least warn if the user tries to pass in one of the reserved function names.

**Comment by taion** [comment]
Thanks!

BTW, as implemented, it looks like it'd be possible to mutate the config passed in after the fact to change the container behavior. It might be cleaner and more performant to branch on the existence of the functions in the config at container class generation time, rather than when the relevant methods are called. I can send in a PR for this if you think it makes sense.

Also, as an app design question, do you think it makes sense to put subscribe/unsubscribe methods on the Store? Or should they go on the Queries object?

**Comment by jhollingworth** [comment]
> It might be cleaner and more performant to branch on the existence of the functions in the config at container class generation time, rather than when the relevant methods are called. I can send in a PR for this if you think it makes sense.

Yeah, makes sense. Send a PR :smile: 

> Do you think it makes sense to put subscribe/unsubscribe methods on the Store? Or should they go on the Queries object?

Sorry, don't follow. What are subscribe & unsubscribe for?

**Comment by taion** [comment]
The idea is that I want to periodically poll my backing store for data as long as I have a component mounted. When the component will mount, I want to call some function to set up an interval to poll for server and refresh the local data in the store from the remote. When I unmount the component, I want to tear down the poller. Additionally, I might want to keep track of the number of subscribers for a given query (i.e. count the number of subscriptions and only have one interval poller, and only tear it down when all the subscriptions go away).

So taking the user example from the docs, assuming the User model can update and I want to poll for updates, something like:

```jsx
{
  componentWillMount() {
    UserStore.subscribeUser(this.props.userId);
  },

  fetch: {
    item() {
      return UserStore.getUser(this.props.userId);
    }
  },

  componentWillUnmount() {
    UserStore.unsubscribeUser(this.props.userId);
  }
}
```

My question then is whether this should be calling `UserStore.subscribeUser`, `UserQueries.subscribeUser`, or something else.

(This is much more of a Flux design question than a Marty-specific one)
