### ISSUE TITLE
parseJSON hook doesn't work in Chrome 43

### ISSUE THREAD

**Issue by taion** [jhollingworth/marty#268]
Specifically on this line: https://github.com/jhollingworth/marty/blob/d516e9713a2ce36ba3270dac5918c438ca421d1f/lib/stateSource/inbuilt/http/hooks/parseJSON.js#L10

It fails with an error like: `Uncaught (in promise) TypeError: Cannot set property body of #<Response> which has only a getter`.

Because `Response.body` actually is a property with only a getter. You could replace that line with something like

```js
Object.defineProperty(res, 'body', {value: body});
```

That gets things working again, but it's probably not ideal to try to re-define `body` on the `Response`.

**Comment by jhollingworth** [comment]
damn! thats very annoying. I think we're going to have to remove this. Question is, to me this is a breaking change so should go in v0.10 but at the same time its a bug that should be fixed in v0.9.... What do you think?

**Comment by taion** [comment]
I think the bugfix for 0.9 could be to just use the `Object.defineProperty` hack (maybe only if necessary?). This keeps existing code working, but assuming things don't change before the Chrome release rolls forward, users will have to upgrade Marty to keep things working.

**Comment by jhollingworth** [comment]
Released in v0.9.9
