### ISSUE TITLE
Confused about how to write unit tests

### ISSUE THREAD

**Issue by johnytex** [jhollingworth/marty#270]
First of all, thanks for creating Marty! I'm new to the framework and development in React in general, and the experience has been very positive so far.

The other day I decided to add some unit tests to my application. Since I wanted to keep things simple I decided to use Mocha and run the tests from node initially.

However, when I tried to use a Marty store I got a bunch of warnings about calling methods on a static instance - after coming across the [documentation on isomorphism](http://martyjs.org/guides/isomorphism/index.html) I realised this was because I was running on the server and the store was not initialised with a context.

If I understand correctly, this leaves me with these options:

 * Handle context in my stores, queries, action creators etc., e.g. adding `.for(this)` where appropriate.

 * Run my tests through Karma, meaning I would have to set it up and get it working with Browserify, PhantomJS, Babel and so on.

Ideally I'd like to keep running tests on the server without having to add context handling everywhere. Is there a way to "trick" Marty into thinking it's running in a browser and short-circuit the concurrency handling, for example? 

Thanks in advance!

**Comment by oliverwoodings** [comment]
I would thoroughly recommend just taking the jump and setting up Karma. As soon as you want to start unit testing your UI components you will need to anyway, so why waste time trying to short-circuit?

Few things you will need to get going:

* Karma with a basic setup
* A karma runner (just use the Chrome one, no need to mess around with PhantomJS)
* Karma-browserify
* Babelify (as you probably already have running)

Here is a basic example of a Karma config file for a React-based browserify UI:

```js
module.exports = function (config) {
  config.set({
      basePath: "",
      frameworks: ["mocha", "browserify"],
      browserify: {
        debug: true,
        bundleDelay: 1500,
        transform: ["babelify"]
      },
      files: [
        "index.js",
        "lib/*.js*",
        "test/**/*.js*"
      ],
      preprocessors: {
        "lib/*": ["browserify"],
        "index.js": ["browserify"],
        "test/**/*.js*": ["browserify"]
      },
      port: 9876,
      logLevel: config.LOG_INFO,
      reporters: ["spec"],
      browsers: ["Chrome"],
      autoWatch: true,
      singleRun: false,
      colors: true
  });
};
```

**Comment by oliverwoodings** [comment]
If you wanted to get karma running on CI like Travis you may need to use a different runner (i think the firefox one works on Travis out of the box)

**Comment by johnytex** [comment]
@oliverwoodings thanks! 

Initially I was thinking of using [jsdom](https://github.com/tmpvar/jsdom) for testing components, but maybe it's easier just to use Karma as you suggested.

**Comment by oliverwoodings** [comment]
If you use Karma you also then have an easy path to setting up with stuff like saucelabs for easy x-browser testing.

Gonna close this for now, feel free to shoot me up if you have any troubles getting karma going.

**Comment by johnytex** [comment]
Thanks again! I'd be more than happy to help out with some docs if I manage to get our testing setup figured out. I saw there are already issues for this (#19 and #57) so let me know if I can help.

**Comment by jhollingworth** [comment]
I've created a repo which shows how you can test Marty v0.10 https://github.com/martyjs/marty-test-examples

**Comment by johnytex** [comment]
Thanks!
