### ISSUE TITLE
Allow you to specify when function context 

### ISSUE THREAD

**Issue by jhollingworth** [jhollingworth/marty#76]
Often you want to [call another component function from within a when handler](https://github.com/jhollingworth/marty-chat-example/blob/master/app/components/room.js#L23-L71). Right now there's no way to set the function context so you end up having to [assigning functions to local variables](https://github.com/jhollingworth/marty-chat-example/blob/master/app/components/room.js#L23).

Ideally you should be able to optionally pass in a function context as the second argument (``when(handlers, context)``). The problem is we already set the [function context to the handlers so that you can call other handlers](https://github.com/jhollingworth/marty/blob/master/lib/when.js#L18).

Not sure how to solve this, needs some thought.

**Comment by oliverwoodings** [comment]
> we already set the function context to the handlers so that you can call other handlers

Do you mean so you can do things like `this.pending()`? If so, is that really that useful? I would have thought being able to access the component scope would be far more useful than the when scope.

**Comment by jhollingworth** [comment]
This is has been implemented in v0.9 (#184)
