### ISSUE TITLE
Broken `this` when disconnecting function from it's calling parens

### ISSUE THREAD

**Issue by spicydonuts** [jhollingworth/marty#91]
The problem is here: [state.js:41](https://github.com/jhollingworth/marty/blob/master/lib/state.js#L41)

When `store.serialize` is `undefined`, `store.getState` is called with a broken `this` reference.

Here's a simplified recreation of the problem:
```js
var x = {
  fn: function () { return this; }
};

x.fn() // => returns `x`

(x.fn)() // => returns `x`

(undefined || x.fn)() // => returns `window` ... wat
```

I think we can all conclude that JavaScript is retarded.  Probably still needs to be fixed though.. : ]

**Comment by spicydonuts** [comment]
Actually, the problem may have been that I wrote my own `getState` function when defining a store.  Maybe `createStore` should warn when you're hiding properties it expects to own.

**Comment by jhollingworth** [comment]
I've made getState a reserved function so you can't reimplement it (We already did this for ``dispose`` and ``clear``)

**Comment by spicydonuts** [comment]
Ok, thanks.  It'd be nice if the Store docs listed reserved names and/or gave a console warning when you override them.

**Comment by jhollingworth** [comment]
Good idea, added to 34e4d7f and in [v0.8.8](https://github.com/jhollingworth/marty/tree/v0.8.8)
