### ISSUE TITLE
`http.js` helper doesn't handle "no content" responses properly

### ISSUE THREAD

**Issue by spicydonuts** [jhollingworth/marty#99]
[`isJson`](https://github.com/jhollingworth/marty/blob/master/lib/stateSources/http.js#L43) assumes `contentTypes` will either be an array or a single item.  When I receive a `204 NoContent`, there is no "Content-Type" header and `contentTypes` is `undefined`.  It then gets placed in a new array and the `map` call on the next line fails.

**Comment by jhollingworth** [comment]
Fixed by #101
